name: "TruffleHog Secret Scan"

on:
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: TruffleHog Scan (Git + Filesystem)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug
