name: secrets_scan

on:
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        continue-on-error: true
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --results=verified,unknown --debug --fail --github-actions
      - name: Fail if secrets found
        if: steps.trufflehog.outcome == 'failure'
        run: |
          echo "::error::Trufflehog found secret!"
          exit 1
